
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# SSL (LE) settings
http:
  base_url: !secret base_url
  # now through nginx
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

# Include Z-wave
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00

# Example configuration.yaml entry
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - switch
    - light

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
